=== LryGean/XML/test1/school.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--school-->
<!--
|:互斥
?:可有可无
-->
<!ELEMENT school (class+)>
<!ELEMENT class (student+)>
<!ELEMENT student (name+,sex,sno,age?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT sex EMPTY>
<!ELEMENT sno (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!--#REQUIRED-->
<!ATTLIST student sno ID #REQUIRED>
<!ATTLIST student sex (M|F) "F">

=== LryGean/XML/test1/school.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE school SYSTEM "school.dtd">
<school>
	<class>
		<student sno="S123">
			<name>张三</name>
			<sex="F"></sex>
			<age>20</age>
		</student>
		<student sno="s124" sex="F">
			<name>李四</name>
			<sex>
			<age>20</age>
		</student>
	</class>
</school>
